# Generated by Django 3.0.3 on 2020-02-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Başlık bilgisi burada girilir.', max_length=100, null=True, verbose_name='Başlık Giriniz')),
                ('icerik', models.TextField(max_length=1000, null=True, verbose_name='İçerik Giriniz')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
