# Generated by Django 3.0.3 on 2020-04-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200418_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20, verbose_name='Kategori İsim')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
    ]
