# Generated by Django 3.0.3 on 2020-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_kategoriler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='kategoriler',
            field=models.ManyToManyField(null=True, related_name='blog', to='blog.Kategori'),
        ),
    ]
