# Generated by Django 3.0.3 on 2020-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200425_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to='', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='kategoriler',
            field=models.ManyToManyField(blank=True, related_name='blog', to='blog.Kategori'),
        ),
    ]
