# Generated by Django 3.0.3 on 2020-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200425_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/default.png', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to='blog', verbose_name='Resim'),
        ),
    ]
