# Generated by Django 2.2.3 on 2020-05-01 14:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200501_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim')),
                ('soyisim', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyisim')),
                ('email', models.EmailField(help_text='Bu alanın girilmesi zorunludur.', max_length=254, null=True, verbose_name='Email')),
                ('icerik', ckeditor.fields.RichTextField(help_text='Yorum Belirtiniz', max_length=1000, null=True, verbose_name='Yorum')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
    ]
