# Generated by Django 2.2.3 on 2020-05-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_yorum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yorum',
            options={'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AddField(
            model_name='yorum',
            name='yorum_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
