# Generated by Django 2.2.3 on 2020-05-16 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0024_auto_20200516_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorum',
            name='email',
        ),
        migrations.RemoveField(
            model_name='yorum',
            name='isim',
        ),
        migrations.RemoveField(
            model_name='yorum',
            name='soyisim',
        ),
        migrations.AddField(
            model_name='yorum',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='icerik',
            field=models.TextField(max_length=1000, null=True, verbose_name='Yorum'),
        ),
    ]
